# Fipkart-products Recommendation Systems
## Content-Based Recommender Systems
## Nearest Neighbors Algorithm

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import NearestNeighbors

*mtcars dataset source:* 
Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391–411.

In [11]:
products = pd.read_csv('data/flipkart_com-ecommerce_sample.csv')
products.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [16]:
products['description'].replace(np.NaN, '', inplace=True)

In [4]:
products[products['uniq_id'] == 'ebd53621ef37807f0d60dbde419a1189']['description']

553    
Name: description, dtype: object

In [5]:
data = products.ix[:,10].values
target = products.ix[:,0].values

/Users/tul/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


# Import Predictor

In [26]:
# #nbrs = NearestNeighbors(n_neighbors=1).fit(X)
# from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
# from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
# text_clf_svm = Pipeline([('vect', CountVectorizer()),
#                       ('tfidf', TfidfTransformer()),
#                       ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, n_iter=5, random_state=42)),
# ])
# text_clf_svm = text_clf_svm.fit(data, target)


tfidf        = TfidfVectorizer(smooth_idf=False)
tfidf_vector = tfidf.fit_transform(products['description'])
clf = SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, n_iter=5, random_state=42)
clf.fit(tfidf_vector)




/Users/tul/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:73: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


TypeError: fit() missing 1 required positional argument: 'y'

In [7]:
#distances, indices = nbrs.kneighbors(t)
#print(distances, indices)
predicted = text_clf.predict(['Back Pack'])

NameError: name 'text_clf' is not defined

In [ ]:
products.head(32)

In [39]:
products[products['uniq_id'] == '3fe211a03baa2c53a26ac58f8e6a4552']

uniq_id            crawl_timestamp  \
16666  3fe211a03baa2c53a26ac58f8e6a4552  2015-12-06 03:01:47 +0000   

                                             product_url  \
16666  http://www.flipkart.com/jadeblue-men-s-solid-f...   

                            product_name  \
16666  JadeBlue Men's Solid Formal Shirt   

                                   product_category_tree               pid  \
16666  ["Clothing >> Men's Clothing >> Shirts >> Form...  SHTEDAZ5D6YZYZHY   

       retail_price  discounted_price  \
16666        1399.0            1399.0   

                                                   image  \
16666  ["http://img5a.flixcart.com/image/shirt/c/m/c/...   

       is_FK_Advantage_product  \
16666                    False   

                                             description       product_rating  \
16666  JadeBlue Men's Solid Formal Shirt\n           ...  No rating available   

            overall_rating    brand  \
16666  No rating available  Regular   

                                  product_specifications  
16666  {"product_specification"=>[{"key"=>"Pattern", ...

In [143]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

products = pd.read_csv('data/flipkart_com-ecommerce_sample.csv')
products.dropna()
target = products.iloc[:,0].values
products['description'].replace(np.NaN, '', inplace=True)
products.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [31]:
products['description'].head()

0    Key Features of Alisha Solid Women's Cycling S...
1    FabHomeDecor Fabric Double Sofa Bed (Finish Co...
2    Key Features of AW Bellies Sandals Wedges Heel...
3    Key Features of Alisha Solid Women's Cycling S...
4    Specifications of Sicons All Purpose Arnica Do...
Name: description, dtype: object

In [34]:
products['retail_price'].head()

0      999.0
1    32157.0
2      999.0
3      699.0
4      220.0
Name: retail_price, dtype: float64

In [137]:
tfidf        = TfidfVectorizer(smooth_idf=False)
tfidf_vector = tfidf.fit_transform(products['description'])
tfidf_vector.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

ValueError: all the input arrays must have same number of dimensions

In [138]:
tfitf_array = tfidf_vector.toarray()


In [129]:
products['retail_price'].head()

0      999.0
1    32157.0
2      999.0
3      699.0
4      220.0
Name: retail_price, dtype: float64

In [116]:
tfitf_array.shape

(20000, 26470)

In [123]:
np.reshape(products['retail_price'], [-1, 1])

/Users/tul/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)


array([[   999.],
       [ 32157.],
       [   999.],
       ..., 
       [  1299.],
       [  1499.],
       [  1499.]])

In [139]:
new_feature = np.concatenate([tfitf_array, np.reshape(products['retail_price'], [-1, 1])], axis=1)

/Users/tul/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)


In [140]:
new_feature

array([[     0.,      0.,      0., ...,      0.,      0.,    999.],
       [     0.,      0.,      0., ...,      0.,      0.,  32157.],
       [     0.,      0.,      0., ...,      0.,      0.,    999.],
       ..., 
       [     0.,      0.,      0., ...,      0.,      0.,   1299.],
       [     0.,      0.,      0., ...,      0.,      0.,   1499.],
       [     0.,      0.,      0., ...,      0.,      0.,   1499.]])

array(['c2d766ca982eca8304150849735ffef9',
       '7f7036a6d550aaa89d34c77bd39a5e48',
       'f449ec65dcbc041b6ae5e6a32717d01b', ...,
       '93e9d343837400ce0d7980874ece471c',
       '669e79b8fa5d9ae020841c0c97d5e935',
       'cb4fa87a874f715fff567f7b7b3be79c'], dtype=object)

In [130]:
clf = SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, n_iter=5, random_state=10)

/Users/tul/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:73: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


In [144]:
clf.fit(new_feature, target)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import NearestNeighbors

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

products = pd.read_csv('data/flipkart_com-ecommerce_sample.csv')
products = products[['description', 'retail_price']].dropna()


products['description'].replace(np.NaN,  '', inplace=True)
# products['retail_price'].replace(np.NaN, 0, inplace=True)
target = products.iloc[:,0].values

tfidf        = TfidfVectorizer(smooth_idf=False)
tfidf_vector = tfidf.fit_transform(products['description'])
tfitf_array  = tfidf_vector.toarray()

new_feature = np.concatenate([tfitf_array, np.reshape(products['retail_price'], [-1, 1])], axis=1)

/Users/tul/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)


In [24]:
new_feature

array([[     0.,      0.,      0., ...,      0.,      0.,    999.],
       [     0.,      0.,      0., ...,      0.,      0.,  32157.],
       [     0.,      0.,      0., ...,      0.,      0.,    999.],
       ..., 
       [     0.,      0.,      0., ...,      0.,      0.,   3999.],
       [     0.,      0.,      0., ...,      0.,      0.,   1799.],
       [     0.,      0.,      0., ...,      0.,      0.,   1415.]])

In [ ]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, n_iter=5, random_state=10)
clf.fit(new_feature, target)

/Users/tul/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:73: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


array([[     0.,      0.,      0., ...,      0.,      0.,    999.],
       [     0.,      0.,      0., ...,      0.,      0.,  32157.],
       [     0.,      0.,      0., ...,      0.,      0.,    999.],
       ..., 
       [     0.,      0.,      0., ...,      0.,      0.,   1299.],
       [     0.,      0.,      0., ...,      0.,      0.,   1499.],
       [     0.,      0.,      0., ...,      0.,      0.,   1499.]])